INCC_M = "incc-m"
IGP_M = "igp-m"
IGP_DI = "igp-di"
IPCA = "ipca"
INPC = "inpc"
SINAPI = "sinapi"
SELIC = "selic"
CDI = "cdi"
PTAX_USD = "ptax-usd"
TAXA_FINANC_IMOB = "taxa-financ-imob-pf"
ANP_DIESEL = "anp-diesel"
PIB = "pib-trimestral"
IFIX = "ifix"
IBOVESPA = "ibovespa"
IMOB = "imob"

FONTE_FGV = "FGV/IBRE"
FONTE_IBGE = "IBGE"
FONTE_BACEN = "BACEN"
FONTE_ANP = "ANP"
FONTE_B3 = "B3"

UNIDADE_PERCENTUAL = "%"
UNIDADE_REAIS_LITRO = "R$/litro"
UNIDADE_TAXA = "% a.a."
UNIDADE_TAXA_MENSAL = "% a.m."
UNIDADE_REAIS_USD = "R$/USD"
UNIDADE_PONTOS = "pts"
