import os

DADPUBAPI_STORAGE_TABLE_URL = os.environ.get("DADPUBAPI_STORAGE_TABLE_URL", "")
DADPUBAPI_FGV_USER = os.environ.get("DADPUBAPI_FGV_USER", "")
DADPUBAPI_FGV_PASSWORD = os.environ.get("DADPUBAPI_FGV_PASSWORD", "")
